### ISSUE TITLE
Windows: Error: Illegal char <"> at index 0

### ISSUE THREAD

**Issue by blackjyn** [gluonhq/client-samples#76] opened 2020-05-01 06:32 UTC
I'm trying to compile [the samples](https://github.com/gluonhq/client-samples) with the following env:
- Windows x64
- GraalVM v20
- MSVC 2017

All are fine , I can even see that Graal has compiled the source to *.class file under the target/* folder.
However when it tried to compile with **native-image** I got:
`[Fri May 01 13:08:44 ICT 2020][INFO] We will now compile your code for x86_64-mi
crosoft-windows. This may take some time.
java.nio.file.InvalidPathException: Illegal char <"> at index 0: "D:\Repo\JavaFX
\gluon-client-substrate-samples\Maven\HelloFXML\target\classes
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.ja
va:182)
[INFO] ------------------------------------------------------------------------
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:1
53)
[INFO] BUILD FAILURE
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:7
7)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
[INFO] ------------------------------------------------------------------------
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java
:229)`

So I then [in probably damn stupid way] tried to compile it manually using native-image to that resulted class location but no luck. 

Solution?

**Comment by tiainen** [comment] 2020-05-04 20:16
Duplicate of https://github.com/gluonhq/substrate/issues/568

**Closed by tiainen** 2020-05-04 20:16 UTC
