### ISSUE TITLE
Link Error. [fatal error LNK1181: cannot open input file]

### ISSUE THREAD

**Issue by KopeMorta** [gluonhq/client-samples#96] opened 2020-07-04 04:02 UTC
I have problems with building native-image on windows 10.
Compilation is successful but on linking have fail with fatal error LNK1181: cannot open input file.

Fail log:
```
[?? ???. 04 06:14:21 MSK 2020][INFO] We will now compile your code for x86_64-microsoft-windows. This may take some time.
[?? ???. 04 06:14:22 MSK 2020][INFO] [SUB] Warning: Ignoring server-mode native-image argument --no-server.
[?? ???. 04 06:14:25 MSK 2020][INFO] [SUB] [hellofx.hellofxml:17696]    classlist:   2,208.94 ms,  0.96 GB
[?? ???. 04 06:14:27 MSK 2020][INFO] [SUB] [hellofx.hellofxml:17696]        (cap):   1,544.34 ms,  0.96 GB
[?? ???. 04 06:14:28 MSK 2020][INFO] [SUB] [hellofx.hellofxml:17696]        setup:   2,993.18 ms,  0.96 GB
[?? ???. 04 06:14:46 MSK 2020][INFO] [SUB] WARNING GR-10238: VarHandle for static field is currently not fully supported. Static field private static volatile java.lang.System$Logger jdk.internal.event.EventHelper.securityLogger is not properly marked for Unsafe access!
[?? ???. 04 06:14:55 MSK 2020][INFO] [SUB] [hellofx.hellofxml:17696]     (clinit):     568.48 ms,  2.83 GB
[?? ???. 04 06:14:55 MSK 2020][INFO] [SUB] [hellofx.hellofxml:17696]   (typeflow):  13,274.19 ms,  2.83 GB
[?? ???. 04 06:14:55 MSK 2020][INFO] [SUB] [hellofx.hellofxml:17696]    (objects):  11,675.64 ms,  2.83 GB
[?? ???. 04 06:14:55 MSK 2020][INFO] [SUB] [hellofx.hellofxml:17696]   (features):   1,524.16 ms,  2.83 GB
[?? ???. 04 06:14:55 MSK 2020][INFO] [SUB] [hellofx.hellofxml:17696]     analysis:  27,690.25 ms,  2.83 GB
[?? ???. 04 06:14:57 MSK 2020][INFO] [SUB] [hellofx.hellofxml:17696]     universe:   1,078.67 ms,  4.05 GB
[?? ???. 04 06:15:00 MSK 2020][INFO] [SUB] [hellofx.hellofxml:17696]      (parse):   3,467.40 ms,  4.05 GB
[?? ???. 04 06:15:06 MSK 2020][INFO] [SUB] [hellofx.hellofxml:17696]     (inline):   5,803.90 ms,  5.40 GB
[?? ???. 04 06:15:24 MSK 2020][INFO] [SUB] [hellofx.hellofxml:17696]    (compile):  18,248.43 ms,  5.68 GB
[?? ???. 04 06:15:26 MSK 2020][INFO] [SUB] [hellofx.hellofxml:17696]      compile:  29,223.71 ms,  5.68 GB
[?? ???. 04 06:15:30 MSK 2020][INFO] [SUB] [hellofx.hellofxml:17696]        image:   3,698.05 ms,  5.63 GB
[?? ???. 04 06:15:30 MSK 2020][INFO] [SUB] [hellofx.hellofxml:17696]        write:     532.80 ms,  5.63 GB
[?? ???. 04 06:15:30 MSK 2020][INFO] [SUB] [hellofx.hellofxml:17696]      [total]:  67,797.27 ms,  5.63 GB
[INFO]
[INFO] --- client-maven-plugin:0.1.27:link (default-cli) @ hellofxml ---
[?? ???. 04 06:15:31 MSK 2020][INFO] ==================== LINK TASK ====================
[?? ???. 04 06:15:32 MSK 2020][INFO] [SUB] Microsoft (R) Incremental Linker Version 14.26.28806.0
[?? ???. 04 06:15:32 MSK 2020][INFO] [SUB] Copyright (C) Microsoft Corporation.  All rights reserved.
[?? ???. 04 06:15:32 MSK 2020][INFO] [SUB]
[?? ???. 04 06:15:32 MSK 2020][INFO] [SUB] LINK : fatal error LNK1181: cannot open input file 'j2pkcs11.lib'
[?? ???. 04 06:15:32 MSK 2020][SEVERE] Process link failed with result: 1181
```

And i found solution, but it's manual linking only.
The fact is that for some reason there is not enough 1 path to libraries.
If add this path to link command - all successful linking to exe.
```
%GRAALVM_HOME%\lib\static\windows-amd64
```

What am I doing wrong, and how do I make it happen automatically?

**Comment by tiainen** [comment] 2020-07-07 07:37
Duplicate of https://github.com/gluonhq/substrate/issues/679

Please update the version of the client-maven-plugin to 0.1.28.

**Closed** 2020-07-09 06:46 UTC
